version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: rbac
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_password
      POSTGRES_DB: rbac_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5431:5432"
    networks:
      - rbac_network
    restart: always


volumes:
  postgres_data:

networks:
  rbac_network:
